### ISSUE TITLE
`<Esc>` mapping should be optional

### ISSUE THREAD

**Issue by JeanMertz** [chottolabs/kznllm.nvim#11]
First, love the plugin. I've been using it in combination with a few other AI-based plugins, and it massively improves my workflow.

One suggestion, I have, is to not include the default `<Esc>` mapping, or at least make it optional.

I had to fork the plugin and remove that mapping as it interferes with my custom mappings (in this case specifically, triggering `nohlsearch` on `<Esc>`).

**Comment by chottolabs** [comment]
> One suggestion, I have, is to not include the default <Esc> mapping, or at least make it optional.

thanks and good suggestion, I should've just bubbled up all mapping related things back into lazy config

>  I've been using it in combination with a few other AI-based plugins, and it massively improves my workflow.

just curious, what other AI plugins are you using?

**Comment by JeanMertz** [comment]
> just curious, what other AI plugins are you using?

Currently: kznllm.nvim, avante.nvim and supermaven.nvim.

I'm still seeing what sticks. Also, while I (really) like supermaven so far for auto-completion/suggestion purposes, I also have subscriptions for Anthropic, TabNine, OpenAI and Co-Pilot (and Llama locally), so preferably I would like some kind of plugin that shows completion suggestions using ghost text (similar to how Supermaven currently works), but then allows me to somehow cycle through suggestions from other providers if the current one isn't what I want.

I tried doing this using nvim-cmp, but it's too cumbersome to have it shown in a small popup without the possibility for multi-line suggestions.

Also still mulling over setting up custom keybindings to e.g. trigger "add documentation to this function", or "suggest refactor for this visual selection" without having to type anything and with the results then showing up in (e.g.) a popup or Telescope prompt to review before accepting.
