### ISSUE TITLE
Visual replace mode cursor is off by one.

### ISSUE THREAD

**Issue by dceluis** [chottolabs/kznllm.nvim#19]
![Peek 2024-09-10 23-44](https://github.com/user-attachments/assets/db18cda9-959b-4064-8e48-751706f5ac4d)

me again today :), I found this small issue when in replace mode. Not quite there yet with lua to fix it myself, unfortunately, but I can try tomorrow  if you could kindly provide some guidance.

Thanks!

**Comment by chottolabs** [comment]
It's probably a very niche use case to do visual instead of visual-lines tbh. 

Unless I prompt it very specifically it has trouble giving useful output, but it was definitely OBO so thanks for spotting it 🙏

I explained how some of the lua and nvim api specific stuff work in the PR if you want to check it out.

**Comment by dceluis** [comment]
Thank you so much for providing some context in the PR comments!

It comes very handy as I was actually wondering if, when using it in normal mode, I could get the plugin to inject the current cursor position into the file contents as a hint to the model.

I found that in normal mode the model doesn't know from which place in the file it's being invoked. So, it then returns the entire code plus the requested additions, and a whole duplicate of the original content is inserted in the middle of the file.

My workaround is to always work in visual mode. Even if that means creating a new line (with some dummy content) to include as the position hint.

**Comment by chottolabs** [comment]
hmm, that does seem like a pretty natural use case for normal mode now that i think of it

i do have a few ideas to play around with in this case

**Comment by dceluis** [comment]
I did a first attempt at sending the cursor position here:

https://github.com/dceluis/kznllm.nvim/commit/0dc83b9892b78bfa28df0a08704e9a153de84abb

Worked pretty well but still not sure if it is the right approach or if you had different ideas.

**Comment by chottolabs** [comment]
> Worked pretty well but still not sure if it is the right approach or if you had different ideas.

yeah this is basically what would be done, something you might consider is just leaving out `M.get_visual_selection_pos` entirely 

since there's no visual selection anyways it basically ends up being a wrapper around this:
```
local _, row, col = unpack(vim.fn.getpos '.')
row, col = row - 1, col - 1
```

then the rest of your code would stay the same

---

The other thing I'm considering is just adding one clear global list of modes because it's getting a little bit confusing how the template changes with various combinations of provided context.

**Comment by dceluis** [comment]
> yeah this is basically what would be done, something you might consider is just leaving out `M.get_visual_selection_pos` entirely

Ah, yes, I missed that entirely.

> The other thing I'm considering is just adding one clear global list of modes because it's getting a little bit confusing how the template changes with various combinations of provided context.

I get what you mean about the difficulty understanding how a template will render, but Im not sure im following `one clear global list of modes`

**Comment by chottolabs** [comment]
> I get what you mean about the difficulty understanding how a template will render, but Im not sure im following one clear global list of modes

kind of the same thought yeah. I just want to make it easier to specialize prompts for certain use cases, but currently features like prefill makes something like "free-form writing" impossible.

**Comment by dceluis** [comment]
I see, well i like the fact that you can just create a new template with custom instructions. it probably wouldnt hurt to add more docs explaining what variables are available to the templates. and also make sure that all templates are getting the same context (unless of course the user has explicitly overridden them, which is an advanced use case anyway so not such a big issue)
