### ISSUE TITLE
better way to manage prompt templates

### ISSUE THREAD

**Issue by chottolabs** [chottolabs/kznllm.nvim#6]
will probably persist them in a user-managed directory

- need a neat way of showing what's actually available to use without cluttering up the screen (i.e. visual selection, "project" context, etc.)
- the way that buffer mode is just dumping the template in every time has to go tbh
- it also desperately needs some proper syntax highlighting
- would like it to be jinja... but am i really going to have to pull that into lua
  - https://github.com/mitsuhiko/minijinja ask the user to download this and we good

**Comment by chottolabs** [comment]
https://github.com/mitsuhiko/minijinja

**Comment by chottolabs** [comment]
project mode about to be so easy...

```
<documents>
{% for file_path in file_paths -%}
   <document index="{{loop.index}}">
      <source>{{file_path}}</source>
      <document_content>
      {% include file_path %}
      </document_content>
   </document>
{%- endfor %}
<documents>
```

**Comment by chottolabs** [comment]
should persist document selections and have a shortcut for adding/removing context

at this point i'm considering a configuration file

**Comment by chottolabs** [comment]
i've come to the realization that this is still really close to a bash one-liner along the lines of this

```
fd incantation | jq $USER_QUERY | minijinja -f json <template> - | curl <api_url> -d {...}
```

we just had to add all this stuff around it to pipe it into the editor + splitting off prompt context into system + user messages (otherwise we could've just done the chat templating all in one go on our own)

**Comment by JeanMertz** [comment]
As an additional note: I'm not using lazy.nvim, but using Nix to manage my plugins. This makes it difficult to get the path to the cloned repository, and thus the `templates` directory.

I had to manually copy/paste the templates to a custom directory, which also means they won't get updated if I update the plugin.

**Comment by chottolabs** [comment]
> I'm not using lazy.nvim, but using Nix to manage my plugins. 

gdi lol, I have yet to play around with nix much at all... the main reason is I still have no idea how the plugin is supposed to get the path to itself without setting a relative path or smth. There has to be some cleaner way to do it.

> I had to manually copy/paste the templates to a custom directory, which also means they won't get updated if I update the plugin.

another refactor might be inbound, so I'll keep this in mind. I'm not super happy with the current state of prompt templates either tbh

appreciate the feedback, thanks

**Comment by JeanMertz** [comment]
> gdi lol, I have yet to play around with nix much at all... the main reason is I still have no idea how the plugin is supposed to get the path to itself without setting a relative path or smth. There has to be some cleaner way to do it.

To be honest, I've mostly moved away from a completely nixified Neovim setup (using Nixvim) to one where I use Nix to build/install Neovim and all plugins (locked to specific versions), and then also install any third-party binaries required by the plugins (think `rg`, `sd`, `fd`, etc.), and then use regular Lua modules to configure everything. Having to split my config between Nix expressions and Lua just wasn't worth the hassle.

> another refactor might be inbound, so I'll keep this in mind. I'm not super happy with the current state of prompt templates either tbh

Perfect 👍
